# Site settings
title: The Human Rights Initiative @ UB
email: admin@hribuffalo.org
description: The Human Rights Initiative @ UB
baseurl: ""
url: "http://hribuffalo.org"
#twitter_username:
#github_username:

# Build settings
markdown: kramdown
